In [2]:
import numpy as np

In [17]:
np.random.seed(1)
arr1=np.random.randint(10,size=(5))
arr2=np.random.randint(10,size=5)

arr1 = arr1 - 2
print(arr1)

arr3 = arr1 + arr2
arr3

arr4 = np. random.randint(10,size=(3,5))

arr5 = arr4 **2

print(arr5)

[ 3  6  7  3 -2]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [28]:
x = np.array([-2,-1,0,1,2])

print(np.abs(x))

x = np.linspace(0,100,5)
x

theta = np.linspace(0,np.pi,3)

print(theta)

print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))



[2 1 0 1 2]
[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [39]:
x = np.arange(1,5)
arr = np.add.reduce(x)
print(arr)

aggr= np.multiply.reduce(x)
print(aggr)


10
24


In [43]:
x = np.arange(1,15)

accum = np.add.accumulate(x)
print(accum)

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105]


In [46]:
np.random.seed(2)
arr = np.random.rand(1000000)

print(np.sum(arr))

%timeit sum(arr)

499468.5166853333
67.3 ms ± 784 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
%timeit np.sum(arr)

1.1 ms ± 68.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [64]:
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.any(arr))
print(np.all(arr))

9
0
4.25
5.0
True
False


In [62]:
np.random.seed(5)

arr= np.random.randint(10,size=(3,4))

print(np.sum(arr, axis=1))

[15 28  8]
