In [6]:
import numpy as np

In [10]:
print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [63]:
np.random.seed(0)
arr1 = np.random.randint(10,size=(3,4,5))
print(arr1)

[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]


In [39]:
np.random.seed(1)
arr = np.random.randint(10,size=(3,4))
print("arr.ndim=",arr.ndim)
print("arr.shape=",arr.shape)
print("arr.size",arr.size)
print("arr dtype=",arr.dtype)
print("arr.itemsize=",arr.itemsize)
print("arr.nbyte=",arr.nbytes)


arr.ndim= 2
arr.shape= (3, 4)
arr.size 12
arr dtype= int32
arr.itemsize= 4
arr.nbyte= 48


array([[5, 8, 9],
       [0, 0, 1]])

In [52]:
np.random.seed(2)
arr = np.random.randint(10,size=(6,8))

arr_sub=arr[:2,:2].copy()
print(arr_sub)

arr

[[8 8]
 [5 4]]


array([[8, 8, 6, 2, 8, 7, 2, 1],
       [5, 4, 4, 5, 7, 3, 6, 4],
       [3, 7, 6, 1, 3, 5, 8, 4],
       [6, 3, 9, 2, 0, 4, 2, 4],
       [1, 7, 8, 2, 9, 8, 7, 1],
       [6, 8, 5, 9, 9, 9, 3, 0]])

In [57]:
arr2= np.arange(10)

grid = arr2.reshape(2,-1)
grid

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

AttributeError: 'list' object has no attribute 'shape'